let
    Source = Web.BrowserContents("https://www.worldometers.info/coronavirus/#countries"),
    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19)"}, {"Column2", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18)"}, {"Column3", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17)"}, {"Column4", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16)"}, {"Column5", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15)"}, {"Column6", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14)"}, {"Column7", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13)"}, {"Column8", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12)"}, {"Column9", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11)"}, {"Column10", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(10):nth-last-child(6), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10)"}, {"Column11", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(10):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(11):nth-last-child(5), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(5), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9)"}, {"Column12", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(10):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(11):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(12):nth-last-child(4), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8)"}, {"Column13", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(10):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(11):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(12):nth-last-child(4) + TH[colspan=""1""][rowspan=""1""]:nth-child(13):nth-last-child(3), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(3), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7)"}, {"Column14", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(10):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(11):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(12):nth-last-child(4) + TH[colspan=""1""][rowspan=""1""]:nth-child(13):nth-last-child(3) + TH[colspan=""1""][rowspan=""1""]:nth-child(14):nth-last-child(2), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(2), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(6)"}, {"Column15", "TABLE[id='main_table_countries_today'] > * > TR > TH[colspan=""1""][rowspan=""1""]:nth-child(1):nth-last-child(15) + TH[colspan=""1""][rowspan=""1""]:nth-child(2):nth-last-child(14) + TH[colspan=""1""][rowspan=""1""]:nth-child(3):nth-last-child(13) + TH[colspan=""1""][rowspan=""1""]:nth-child(4):nth-last-child(12) + TH[colspan=""1""][rowspan=""1""]:nth-child(5):nth-last-child(11) + TH[colspan=""1""][rowspan=""1""]:nth-child(6):nth-last-child(10) + TH[colspan=""1""][rowspan=""1""]:nth-child(7):nth-last-child(9) + TH[colspan=""1""][rowspan=""1""]:nth-child(8):nth-last-child(8) + TH[colspan=""1""][rowspan=""1""]:nth-child(9):nth-last-child(7) + TH[colspan=""1""][rowspan=""1""]:nth-child(10):nth-last-child(6) + TH[colspan=""1""][rowspan=""1""]:nth-child(11):nth-last-child(5) + TH[colspan=""1""][rowspan=""1""]:nth-child(12):nth-last-child(4) + TH[colspan=""1""][rowspan=""1""]:nth-child(13):nth-last-child(3) + TH[colspan=""1""][rowspan=""1""]:nth-child(14):nth-last-child(2) + TH[colspan=""1""][rowspan=""1""]:nth-child(15):nth-last-child(1), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(1), TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(5)"}, {"Column16", "TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(4)"}, {"Column17", "TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(3)"}, {"Column18", "TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(18):nth-last-child(2)"}, {"Column19", "TABLE[id='main_table_countries_today'] > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(19) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(18) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(17) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(16) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(15) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(14) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(13) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(12) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(12):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(13):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(14):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(15):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(16):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(17):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(18):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(19):nth-last-child(1)"}}, [RowSelector="TABLE[id='main_table_countries_today'] > * > TR"]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Extracted Table From Html", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"#", Int64.Type}, {"Country,Other", type text}, {"TotalCases", Int64.Type}, {"NewCases", Int64.Type}, {"TotalDeaths", Int64.Type}, {"NewDeaths", Int64.Type}, {"TotalRecovered", type text}, {"ActiveCases", type text}, {"Serious,Critical", Int64.Type}, {"Tot Cases/1M pop", Int64.Type}, {"Deaths/1M pop", type number}, {"TotalTests", Int64.Type}, {"Tests/#(lf)1M pop", Int64.Type}, {"Population", Int64.Type}, {"Continent", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Table", each "Now")
in
    #"Added Custom"